### ISSUE TITLE
Game crash regarding threaded map generation

### ISSUE THREAD

**Issue by VirtualBrightPlayz** [VirtualBrightPlayz/SLCloneIssues#36]
```
ERR: AsyncTools: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Layout'.
   at Godot.GodotObject.GetPtr(GodotObject instance)
   at Godot.Node3D.get_GlobalPosition()
   at LayoutCell.GetGlobalPosition()
   at MapGenerator.LoadMap()+MoveNext()
   at AsyncTools.State.Tick(Double delta)
```

**Comment by VirtualBrightPlayz** [comment]
```ERROR: System.InvalidCastException: Unable to cast object of type 'Godot.AudioStreamGeneratorPlayback' to type 'Godot.Node'.
   at Godot.Collections.Array`1.get_Item(Int32 index)
   at Godot.Collections.Array`1.GetEnumerator()+MoveNext()
   at RoundManager.LoadMap()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Godot.GodotSynchronizationContext.ExecutePendingContinuations()
   at Godot.Bridge.ScriptManagerBridge.FrameCallback()
   at: void Godot.NativeInterop.ExceptionUtils.LogException(System.Exception) (:0)
```

**Comment by VirtualBrightPlayz** [comment]
Fixed for next patch.
